const FEED='https://data.lpp.si/api/gtfs/feed.zip';
const CFG={origin:'Polje',routes:[['27','Konzorcij'],['11','Drama'],['25','Bavarski dvor']],homeToStop:8,wakeBeforeBus:20,backupBeforeWake:15};
const $=id=>document.getElementById(id), arrival=$('arrival'), find=$('find'), status=$('status'), results=$('results');
const toMin=t=>{let p=t.split(':').map(Number);return p[0]*60+p[1]}; const fmt=n=>{n=((n%1440)+1440)%1440;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')};
function parseCSV(s){let a=[],r=[],c='',q=false;for(let i=0;i<s.length;i++){let x=s[i],y=s[i+1];if(q){if(x==='"'&&y==='"'){c+='"';i++}else if(x==='"')q=false;else c+=x}else if(x==='"')q=true;else if(x===','){r.push(c);c=''}else if(x==='\n'){r.push(c);a.push(r);r=[];c=''}else if(x!=='\r')c+=x}if(c||r.length){r.push(c);a.push(r)}let h=a.shift().map(x=>x.trim());return a.filter(r=>r.length).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])))}
async function getFeed(){let res=await fetch(FEED,{cache:'no-store'});if(!res.ok)throw Error('LPP feed returned HTTP '+res.status);let zip=new Uint8Array(await res.arrayBuffer());let files=fflate.unzipSync(zip), out={};for(let n of ['routes.txt','stops.txt','trips.txt','stop_times.txt','calendar.txt','calendar_dates.txt']){if(files[n])out[n.slice(0,-4)]=parseCSV(new TextDecoder().decode(files[n]))}return out}
function activeServices(g,date){let ymd=date.getFullYear()+String(date.getMonth()+1).padStart(2,'0')+String(date.getDate()).padStart(2,'0'),dow=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][date.getDay()],s=new Set((g.calendar||[]).filter(x=>x.start_date<=ymd&&ymd<=x.end_date&&x[dow]==='1').map(x=>x.service_id));for(let x of g.calendar_dates||[])if(x.date===ymd)(x.exception_type==='1'?s.add(x.service_id):s.delete(x.service_id));return s}
async function calculate(target){let g=await getFeed(),d=new Date();d.setDate(d.getDate()+1);d.setHours(0,0,0,0);let active=activeServices(g,d),routes=new Map(g.routes.map(x=>[x.route_id,x])),trips=g.trips.filter(t=>active.has(t.service_id)&&CFG.routes.some(x=>x[0]===routes.get(t.route_id)?.route_short_name));let tripIds=new Set(trips.map(t=>t.trip_id));let originIds=new Set(g.stops.filter(s=>s.stop_name?.toLowerCase().includes(CFG.origin.toLowerCase())).map(s=>s.stop_id));let dest={};for(let [line,name] of CFG.routes)dest[line]=new Set(g.stops.filter(s=>s.stop_name?.toLowerCase()===name.toLowerCase()).map(s=>s.stop_id));let by=new Map();for(let st of g.stop_times||[])if(tripIds.has(st.trip_id)){if(!by.has(st.trip_id))by.set(st.trip_id,[]);by.get(st.trip_id).push(st)}let out=[];for(let [line,name] of CFG.routes){let best=null;for(let t of trips.filter(x=>routes.get(x.route_id)?.route_short_name===line)){let ss=(by.get(t.trip_id)||[]).sort((a,b)=>+a.stop_sequence-+b.stop_sequence),oi=ss.findIndex(x=>originIds.has(x.stop_id));if(oi<0)continue;let di=ss.findIndex((x,i)=>i>oi&&dest[line].has(x.stop_id));if(di<0)continue;let dep=toMin(ss[oi].departure_time),arr=toMin(ss[di].arrival_time);if(dep>target||arr>target)continue;let cand={line,name,dep,arr};if(!best||arr>best.arr||(arr===best.arr&&dep>best.dep))best=cand}if(best)out.push(best)}return out}
function render(xs,target){if(!xs.length){results.innerHTML='<section class="card"><b>No suitable scheduled trip found.</b><p>Try a later arrival time or check the timetable manually.</p></section>';return}results.innerHTML=xs.map((x,i)=>{let wake=x.dep-CFG.wakeBeforeBus,leave=x.dep-CFG.homeToStop,backup=wake-CFG.backupBeforeWake,margin=target-x.arr;return `<article class="result good"><div class="line">${i===0?'BEST / PREFERRED':i===1?'ALTERNATIVE':'RARE ALTERNATIVE'}</div><h2>🚌 ${x.line} → ${x.name}</h2><div class="times"><div class="timebox"><span>Bus at Polje</span><b>${fmt(x.dep)}</b></div><div class="timebox"><span>Arrive at ${x.name}</span><b>${fmt(x.arr)}</b></div><div class="timebox"><span>Wake up</span><b>${fmt(wake)}</b></div><div class="timebox"><span>Leave home</span><b>${fmt(leave)}</b></div><div class="timebox"><span>Backup alarm</span><b>${fmt(backup)}</b></div><div class="timebox"><span>Buffer</span><b>${margin} min</b></div></div></article>`}).join('')}
async function run(){find.disabled=true;status.textContent='Loading the current LPP timetable…';results.innerHTML='';try{let t=toMin(arrival.value||'07:00'),x=await calculate(t);status.textContent=`Tomorrow • ${x.length} suitable option${x.length===1?'':'s'} found`;render(x,t)}catch(e){console.error(e);status.textContent='Could not load the LPP timetable';results.innerHTML='<section class="card"><b>Could not load LPP data.</b><p>Make sure you are online. If it keeps failing, the LPP feed may be temporarily unavailable or blocking browser requests.</p></section>'}finally{find.disabled=false}}
find.addEventListener('click',run);run();
